logging:
  file: logs/serviceya.log
  level:
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

spring:

  h2:
    console:
      enabled: true

  datasource:
    initialize: true

  jpa:
    show-sql: true

google:
  maps:
    key: AIzaSyBNJvYQ-t6dymsHr6bI6UtSH9MlB5ujlTk